"""create prototype_master table

Revision ID: 45449723ec55
Revises: dab718b75189
Create Date: 2026-05-30 13:42:15.961890

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45449723ec55'
down_revision: Union[str, Sequence[str], None] = 'dab718b75189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prototype_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_sheets', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_records', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('materials', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_cost_rs', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prototype_master_project_id'), 'prototype_master', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prototype_master_project_id'), table_name='prototype_master')
    op.drop_table('prototype_master')
    # ### end Alembic commands ###
