"""create science_project_records table

Revision ID: 6d2de5732701
Revises: 86e4f74222dc
Create Date: 2026-05-28 19:45:49.278748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d2de5732701'
down_revision: Union[str, Sequence[str], None] = '86e4f74222dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('science_project_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curriculum_alignment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_build_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overall_difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scientific_principle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('simple_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adult_supervision_required', sa.Boolean(), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_science_project_records_grade'), 'science_project_records', ['grade'], unique=False)
    op.create_index(op.f('ix_science_project_records_subject'), 'science_project_records', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_science_project_records_subject'), table_name='science_project_records')
    op.drop_index(op.f('ix_science_project_records_grade'), table_name='science_project_records')
    op.drop_table('science_project_records')
    # ### end Alembic commands ###
