"""create curriculum, project_metadata, and assessment tables

Revision ID: 86e4f74222dc
Revises: 792aa5dd4d11
Create Date: 2026-05-28 18:41:45.752809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86e4f74222dc'
down_revision: Union[str, Sequence[str], None] = '792aa5dd4d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('mcq_count', sa.Integer(), nullable=False),
    sa.Column('vsa_count', sa.Integer(), nullable=False),
    sa.Column('sa_count', sa.Integer(), nullable=False),
    sa.Column('la_count', sa.Integer(), nullable=False),
    sa.Column('easy_pct', sa.Integer(), nullable=False),
    sa.Column('medium_pct', sa.Integer(), nullable=False),
    sa.Column('hard_pct', sa.Integer(), nullable=False),
    sa.Column('marks_distribution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_config_grade'), 'assessment_config', ['grade'], unique=False)
    op.create_table('curriculum_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prerequisites', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_master_grade'), 'curriculum_master', ['grade'], unique=False)
    op.create_index(op.f('ix_curriculum_master_subject'), 'curriculum_master', ['subject'], unique=False)
    op.create_table('project_metadata_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typical_difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typical_materials_count', sa.Integer(), nullable=False),
    sa.Column('estimated_build_time_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_rs', sa.Float(), nullable=False),
    sa.Column('adult_supervision', sa.Boolean(), nullable=False),
    sa.Column('common_materials', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('safety_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_metadata_config_grade'), 'project_metadata_config', ['grade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_metadata_config_grade'), table_name='project_metadata_config')
    op.drop_table('project_metadata_config')
    op.drop_index(op.f('ix_curriculum_master_subject'), table_name='curriculum_master')
    op.drop_index(op.f('ix_curriculum_master_grade'), table_name='curriculum_master')
    op.drop_table('curriculum_master')
    op.drop_index(op.f('ix_assessment_config_grade'), table_name='assessment_config')
    op.drop_table('assessment_config')
    # ### end Alembic commands ###
