"""create children table and add story fields

Revision ID: 93a8be9fd172
Revises: 45449723ec55
Create Date: 2026-07-18 20:26:00.031467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93a8be9fd172'
down_revision: Union[str, Sequence[str], None] = '45449723ec55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nick_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('school_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learning_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('favourite_subjects', sa.JSON(), nullable=True),
    sa.Column('existing_toys', sa.JSON(), nullable=True),
    sa.Column('household_materials', sa.JSON(), nullable=True),
    sa.Column('special_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.add_column('stories', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stories', sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stories', sa.Column('story_mood', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stories', sa.Column('story_length', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stories', sa.Column('today_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_stories_goal'), 'stories', ['goal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_goal'), table_name='stories')
    op.drop_column('stories', 'today_context')
    op.drop_column('stories', 'story_length')
    op.drop_column('stories', 'story_mood')
    op.drop_column('stories', 'goal')
    op.drop_column('stories', 'title')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
