"""create assessment_generation_history table

Revision ID: dab718b75189
Revises: 6d2de5732701
Create Date: 2026-05-30 10:40:10.005748

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab718b75189'
down_revision: Union[str, Sequence[str], None] = '6d2de5732701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_specs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['assessment_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_generation_history_grade'), 'assessment_generation_history', ['grade'], unique=False)
    op.create_index(op.f('ix_assessment_generation_history_pattern_id'), 'assessment_generation_history', ['pattern_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_generation_history_pattern_id'), table_name='assessment_generation_history')
    op.drop_index(op.f('ix_assessment_generation_history_grade'), table_name='assessment_generation_history')
    op.drop_table('assessment_generation_history')
    # ### end Alembic commands ###
