"""add_child_development_platform_tables

Revision ID: e446724c9b38
Revises: c3d4e5f6a7b8
Create Date: 2026-08-08 23:36:17.529480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e446724c9b38'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_development_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('understanding_confidence', sa.Float(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('learning_preferences', sa.JSON(), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('total_signals_processed', sa.Integer(), nullable=False),
    sa.Column('last_insight_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_development_records_child_id'), 'child_development_records', ['child_id'], unique=True)
    op.create_table('child_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_insights_category'), 'child_insights', ['category'], unique=False)
    op.create_index(op.f('ix_child_insights_child_id'), 'child_insights', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_insights_insight_type'), 'child_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_child_insights_is_active'), 'child_insights', ['is_active'], unique=False)
    op.create_table('content_journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_journey_child_id'), 'content_journey', ['child_id'], unique=False)
    op.create_index(op.f('ix_content_journey_content_id'), 'content_journey', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_journey_content_type'), 'content_journey', ['content_type'], unique=False)
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('child_context', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['questionnaire_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_responses_child_id'), 'questionnaire_responses', ['child_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_responses_parent_id'), 'questionnaire_responses', ['parent_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_responses_template_id'), 'questionnaire_responses', ['template_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_category'), 'signals', ['category'], unique=False)
    op.create_index(op.f('ix_signals_child_id'), 'signals', ['child_id'], unique=False)
    op.create_index(op.f('ix_signals_processed'), 'signals', ['processed'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.drop_constraint(op.f('parents_email_key'), 'parents', type_='unique')
    op.drop_constraint(op.f('parents_mobile_number_key'), 'parents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('parents_mobile_number_key'), 'parents', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('parents_email_key'), 'parents', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_processed'), table_name='signals')
    op.drop_index(op.f('ix_signals_child_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_category'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_questionnaire_responses_template_id'), table_name='questionnaire_responses')
    op.drop_index(op.f('ix_questionnaire_responses_parent_id'), table_name='questionnaire_responses')
    op.drop_index(op.f('ix_questionnaire_responses_child_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    op.drop_index(op.f('ix_content_journey_content_type'), table_name='content_journey')
    op.drop_index(op.f('ix_content_journey_content_id'), table_name='content_journey')
    op.drop_index(op.f('ix_content_journey_child_id'), table_name='content_journey')
    op.drop_table('content_journey')
    op.drop_index(op.f('ix_child_insights_is_active'), table_name='child_insights')
    op.drop_index(op.f('ix_child_insights_insight_type'), table_name='child_insights')
    op.drop_index(op.f('ix_child_insights_child_id'), table_name='child_insights')
    op.drop_index(op.f('ix_child_insights_category'), table_name='child_insights')
    op.drop_table('child_insights')
    op.drop_index(op.f('ix_child_development_records_child_id'), table_name='child_development_records')
    op.drop_table('child_development_records')
    op.drop_table('questionnaire_templates')
    # ### end Alembic commands ###
