"""Child Insight model — derived understanding from processed signals."""

from datetime import datetime

from sqlalchemy import Column, JSON
from sqlmodel import Field, SQLModel


class ChildInsight(SQLModel, table=True):
    """A derived insight about a child from signal analysis.

    Insights are generated by the Child Understanding Engine from
    processed signals. They represent strengths, gaps, preferences,
    or developmental milestones.
    """

    __tablename__ = "child_insights"

    id: int | None = Field(default=None, primary_key=True)
    child_id: int = Field(foreign_key="children.id", index=True, nullable=False)

    # ── Insight Classification ────────────────────────────────────────
    insight_type: str = Field(
        nullable=False,
        index=True,
        description="strength, gap, milestone, preference, concern",
    )
    category: str | None = Field(
        default=None,
        index=True,
        description="Domain (e.g. motor_skills, verbal, social, cognitive)",
    )

    # ── Insight Content ───────────────────────────────────────────────
    description: str = Field(nullable=False, description="Human-readable insight")
    evidence: list | None = Field(
        default=None,
        sa_column=Column(JSON),
        description="Signal IDs or data points that support this insight",
    )
    confidence: float = Field(
        nullable=False,
        description="0.0-1.0 confidence in this insight",
    )

    # ── Lifecycle ─────────────────────────────────────────────────────
    is_active: bool = Field(default=True, index=True, description="Soft delete / superseded")
    superseded_by_id: int | None = Field(
        default=None,
        description="ID of the insight that replaced this one",
    )
    expires_at: datetime | None = Field(
        default=None,
        description="When this insight should be re-evaluated",
    )

    # ── Timestamps ────────────────────────────────────────────────────
    generated_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
    created_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)
